### 매장 등록(1)
POST http://localhost:8080/register/store
Content-Type: application/json

{
  "storeInfo": {
    "name": "helloStore",
    "address": {
      "city": "busan",
      "street": "buk-gu"
    },
    "description": "this is helloStore"
  },
  "managerId": "mng123"
}

### 매장 등록(2)
POST http://localhost:8080/register/store
Content-Type: application/json

{
  "storeInfo": {
    "name": "abcStore",
    "address": {
      "city": "seoul",
      "street": "mapo-gu"
    },
    "description": "this is abcStore"
  },
  "managerId": "abc123"
}

### 모든 매장 찾기
GET http://localhost:8080/store
Content-Type: application/json

### 자동완성 매장 찾기
GET http://localhost:8080/search/store?name=ron
Content-Type: application/json
