### 예약(1)
POST http://localhost:8080/reserve
Content-Type: application/json

{
  "storeName": "kanginStore",
  "customer": {
    "userId": "messi123",
    "password": "0000"
  },
  "headCount": 11,
  "dateTime": "2023-08-01 12:00:00"
}

### 예약(2)
POST http://localhost:8080/reserve
Content-Type: application/json

{
  "storeName": "kanginStore",
  "customer": {
    "userId": "pyree123",
    "password": "0000"
  },
  "headCount": 3,
  "dateTime": "2023-08-01 12:00:00"
}

### 예약(3)
POST http://localhost:8080/reserve
Content-Type: application/json

{
  "storeName": "neymarStore",
  "customer": {
    "userId": "son123",
    "password": "0000"
  },
  "headCount": 7,
  "dateTime": "2023-08-01 12:00:00"
}