### Use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 500
}

### Use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 500
}


###

POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "5fb996cd058d465b83d3bfcd917fbdde",
  "accountNumber": "1000000000",
  "amount": 500
}
###

GET http://localhost:8080/transaction/2b10dc13ae124c7cae0e549ad0b54197
Content-Type: application/json

