spring:
  redis:
    port: 6379
    host: localhost
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

# h2 console을 브라우저에서 접속할수 있게
  h2:
    console:
      enabled: true

  jpa:
    # 초기데이터 입력을 진행할 수 있도록 하는 옵션
    # 이 옵션이 없으면 테이블 생성전에 초기데이터 입력을 하려고 하게됨
    defer-datasource-initialization: true
    database-platform: H2
    encoding:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# yml 한글 인코딩
server:
  servlet:
      force-response: true